Jacobs University
Machine Learning

Sabeeh ur Rehman Sulehri

Declaring and Initializing the Data(matrices) and libraries needed.

In [7]:
import numpy as np

a = np.array([1,1,0])
b = np.array([-1,2,5])

M = np.array([[2,-1,0],
              [-1,2,-1],
              [0,-1,2]])

print("a=",a," b=",b,"\n M=\n",M)

a= [1 1 0]  b= [-1  2  5] 
 M=
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


Computing the inner product between a and b.

In [8]:
print(np.dot(a,b))

1


Computing the Matrix-Vector product between M and b.

In [9]:
print(M*b)

[[-2 -2  0]
 [ 1  4 -5]
 [ 0 -2 10]]


Computing the L2 norm of b.

In [11]:
print(np.linalg.norm(b))

5.477225575051661


Computing and printing the the solution x of the linear system of equations Mx = b using the LU factorization.

In [14]:
import scipy.linalg as la

LU = la.lu_factor(M)
print(LU)

x = la.lu_solve(LU,b)
print(x)

np.allclose(np.dot(M,x), b)

(array([[ 2.        , -1.        ,  0.        ],
       [-0.5       ,  1.5       , -1.        ],
       [ 0.        , -0.66666667,  1.33333333]]), array([0, 1, 2], dtype=int32))
[1.5 4.  4.5]


True

Computing and printing the the solution x of the linear system of equations M x = b using the Cholesky factorization.

In [15]:
LU = la.cho_factor(M)
print(LU)

x = la.cho_solve(LU,b)
print(x)

(array([[ 1.41421356, -0.70710678,  0.        ],
       [-1.        ,  1.22474487, -0.81649658],
       [ 0.        , -1.        ,  1.15470054]]), False)
[1.5 4.  4.5]


We can clearly see that the answer is the same for Mx=b whether done by LU factorization or Cholesky factorization.